// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_T5wu3iSCCtOoXGJo5RnZIdBuj2pMO_I',
    appId: '1:527882203234:web:4713e82360e59819a9613b',
    messagingSenderId: '527882203234',
    projectId: 'sims-dev-47238',
    authDomain: 'sims-dev-47238.firebaseapp.com',
    storageBucket: 'sims-dev-47238.firebasestorage.app',
    measurementId: 'G-DZJL71XWCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUkpXkZfErTfeOxeREU7LWVfgZIa0N6kU',
    appId: '1:527882203234:android:848bab0ca43682e8a9613b',
    messagingSenderId: '527882203234',
    projectId: 'sims-dev-47238',
    storageBucket: 'sims-dev-47238.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMdiJAnG2Jv1CbxF7uw6R3UD2Hx0SkAYE',
    appId: '1:527882203234:ios:babeea259bfe5ea8a9613b',
    messagingSenderId: '527882203234',
    projectId: 'sims-dev-47238',
    storageBucket: 'sims-dev-47238.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );
}
